name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run type-check
      - run: npm run build
        env:
          DATABASE_URL: postgresql://flowchart:flowchart@127.0.0.1:5432/flowchart
          NEXT_PUBLIC_APP_URL: http://localhost:3000
